server {
    # configuración en el puerto 80
    listen 80;
    server_name localhost;

    # Define cómo manejar las peticiones de los archivos estáticos
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Redirección de errores estándar
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}